apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:aftyF3LgqZ/L2eO/pj+rc9sg1l4M3qDsQRUbIm5HOv4CP4XADTllPU6rpfwJbRbYMB4DKD5jScLBAxWbF0iLa9BFJ9BuoQ2+t966gDqXTfgJ4u1Phx9eL3Im+JjpJcK8REuCDV9p81grsyE5ZYuw+5PLqzW1ZrUnAsR8T91ahA6Wx0Tup1vgvHgzv02wy2Lm/20i/c5nvYtv0btM1Wad3dMpw6Xjt2dabjIhHnwdW19sguIG1O/uxpaxxsuxgZYj9bkeIegelBV6vUq5yM8OohIhs/llFDOgT3eI3T5aQsarJAti7YSgUkD68tg=,iv:PT+hV8XWBPWcg/rDiX/hRAmcCzeOgqSFvetdY1elB30=,tag:KvAaD0ncxPaczQgjlvTZqg==,type:str]
kind: Secret
metadata:
    name: tunnel-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmptdXhTRUpHUG1xeXVK
            UnJER3dXUG1BNStYL045R3VzdDhEQlZ3ejIwCmpORjMyOUJLKy9GSTlycER6dkRm
            dkJXSXo0aVFlbEVJUU9WanJ1MmErR28KLS0tIFVmTHluVEVqamlpWEk3b3V1WFk3
            ajBvTmlidktpaUpsVkNwanNjbHRDUm8Ke/FGk3yzAI7sFmFR/hjTEbMb77g7gaZp
            TWrsD5yxGkj8xan+s+Ld36P+Gy6uaGamGq2GzSNks8lTv5WjBmMd0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfc40eatmnux48n6mcz5vuczpmkyy4h08lnqugqnlt04kafqr9xqah45hc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T08:49:23Z"
    mac: ENC[AES256_GCM,data:dvcV4VpdfjstatmYSCiAMv9u6hjt4O99fik2rCZch3DVopTaM7NtyWZpadKSKRXxySo2tmlPyIZcIAb1f3dDv41FH3Y2snhYfg6ojVeyI8y9sIPn2YcsyXqTLu6N5JEQfRXuoCd26wWKeSbNxdk49wZwAsPX7AoxcMTzzlkgFS4=,iv:WMw6VcCmD5QQkgMAQDCtT0oa7jEFHFVNxrla7352QC0=,tag:/8hCWSDVDT+85quv7/GW6A==,type:str]
    version: 3.13.3
