creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age14tfrmysjuq6qjr5edv09ypc0hvkjtj2wny7mg03xq554xmx553kqn34u52,age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
