apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Y5xN0UCy7YaNAcYjF0ILX+BG5A/RYjFCsZbryOgCPWR5kupjliZnDmPtowTNOcRSjIb3Lnm929rDbB9p3btElydPdYskDCWDHnbyPlkh2yU0ke9+yMntuJ0Jjn+eF5OBfmtr2ahp0vMS61qPvwAdx4ePn4rVH9bngNOfDe1EE9Uc125cRnbI/HtbIf2rkI9yWIIvJsFolcP5GF1556rgEoPH6MHLQXTm2gMlxlO3euxMw4Vv/APOrqrU14Ygcx6FKRb7VKX/9hctv3MAWkbR3Nze70vjhmjMS16wgDyG2yhqEqyBZFkIV9P8Ezc=,iv:cbEkF9boCUzYVxV+9ppa4YoUdPIN7eRGHCoU0Ia7Hgo=,tag:Xlb2pLrHOIcgxqkQQ1MWLw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-07-31T09:06:43Z"
    name: tunnel-credentials
    resourceVersion: "89349"
    uid: 2a311cea-1523-403f-a3dc-05d049a672d8
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRXVZWE9tamtjZnEzaTND
            WkhVN2hZQUhBY0RqVmhEN04zWnh1UlptSUVZCkhSZGNvdlFuWllyRnRwaUlTNCtB
            S0xTaU41SWk4YUsvOUNKYUgzYlZxbjgKLS0tIGRhU2RTQk9LSlMxUlE4NEpKOFdt
            Q3lJWjZFQVc2N1AwOFppa3ZWSnhUbDAKgeNUDqF1rf+bHJxfgDr10hcVdwxp27Tx
            QwUuQr2dzjFhz3wUtYBe2lNqVb5ba4lymWAsXoJyf437uTjsrgeqfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tfrmysjuq6qjr5edv09ypc0hvkjtj2wny7mg03xq554xmx553kqn34u52
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQS9sSU0yWnluU0dKUXU1
            bXNnanYyWFBzT1B3UkhBblB5V2dNRzZJN1NZCmpRUnlPVklyOGRmTlVLc2dkY0Nh
            cGxQbmUvRUZkUjVZSXRDcFNoK2taaWMKLS0tIFZTMnIxRG5FbkZrRlVUNlNoMzJx
            b25OTWFTbHhxNnI5UVhKTS9uZFhFUkEKrI6PZ4MVP4ZVT/H9nhBbP1humxSJ8Bqn
            gXaRm+IDwprFlCddkC/EpHOyT72VcZ6euL6ifeLo+Db2IwQW9HiiBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T09:08:07Z"
    mac: ENC[AES256_GCM,data:V1/JAV66eu9vxP6850fGMs5nrY2hV3Fq5thhvRgDbed0yHQRjYnpHFCdr7lhfQ4vfV4O2jUVDn9AqRzLScre5Wurf35LU3nf5bP6tXfHfvnMeZBBiUBhRsf4yxAJOTRiPYq0eNTcfT0fuKfOliY3kh+7xwcy70fhIZ05HnkBBN0=,iv:x+X4ew9yDKSxL3AdyznnrikSSqkBQfrCj6x7E70+d4Q=,tag:Kx3ap2dKPkM6q//lbGBPUQ==,type:str]
    version: 3.13.3
