apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Fz3MZbnSKPM3OiUUSHQz+KRJNH9LkCcqV5bg0+sW8YRCVVmdkPmLHMZScoau/+ThktV8qNteShlxGMfJUsO2JBC56C4qmmjrVxHu6ue1ReBTGpp9aPex3xdaARYbGP+Jy5nc01itO8nKbU5XTxmUV5PiAq30xL3hkzqCdL/2rgDsl9KdxTobfweTuJFlKI+cwQwnDmqAl0hdw7aeQ2vzBA9gDBYu7aLKuULz5AlTrzCdX4b05+DwBM6iQk+MtdgIVnzaBpwY7xkdqtzsGPWasRDz5N8ulW6iZmroJ1RE2s/RFIaK8f257Hog1ys=,iv:+xzmtmwsheiNPgadU7gndPb+DDX6KEUVYhV6LbDU6WM=,tag:V3sC/5zaWH0AQdPTElNrVg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSzVxdVpTcmY3bTVDcmVD
            WC9KQzhzUzNwcHNxamJHOW9vTFYxMExzQkdzCi9VanlQQ3VMU3ArZHJZM2Q5Rk1F
            dlpVZC9HTHBUWHNvYzJHUm1WMVlRNHcKLS0tIFYwTDR6NG1xTmQxZlRSdmhJaEJ6
            RjgxalkrQ2ZOOGdPNHBvNXM5aDVpaTgKc+744fkXEOuhRk2wa5+tPdOs15ZukTpx
            OISdoDvVBmpkoLrNKc03lq0ph/2uf8ereZNEsY9oYVn9gCtbq44k7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T09:21:35Z"
    mac: ENC[AES256_GCM,data:Njt7fREDTAlVZBI5AASH+KdcinjN9DoBhLxDLsxEfiNtlibprr8QhZImvSkYxoej1oEUQkrJH9OV1PALfGEafdn/E1ZEpn6Nvo4XlQwWyHU0cYcuW5Sz1d3QiJMeaLbEAjnoGRHFdU6gdS+EYFp07qJXWbshaIb/BCjK2by2MCA=,iv:+2cuwLSNgs3bFzrn1o07i+owM77iIOqKSc661GNOQJM=,tag:ysVsZFUCGcdJBuD5tT8+Ag==,type:str]
    version: 3.13.3
