apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.35.0

          envFrom:
            - configMapRef:
               name: audiobookshelf-configmap

          volumeMounts:
            - name: config
              mountPath: /etc/audiobookshelf/config
            - name: metadata
              mountPath: /etc/audiobookshelf/metadata
            - name: audiobooks
              mountPath: /etc/audiobookshelf/audiobooks
            - name: podcasts
              mountPath: /etc/audiobookshelf/podcasts

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvci

      securityContext:
        allowPrivilegeEscalation: false
