apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LXlQy6csce9Ld8pCCwiZYconacEliUOinTOFJysHt5zPvGHkf+7uvu9yLFTkHBNunGZS59PPSc+s+9g0mohENrlciuLJNkNgjKALA0dRyriU8+mECZmoQ2JB9t5ZdQDMjlmIxUUEVXdzBPsmF8sZblmZ4yUcbUP+0i8DsEQ1N+svYQ4A1x79IYqLVDshoFFjVDMySt39VEdw0vpF6SZhInnNXYEKfwHY3ovrrhlbqbB57s9QsRwYgB0YcP8k2jSDRJij5Bll0Y6DFqiS8TfvmDCAXd6hIr0t/AA6m+JNzG8GkCwRfWP1JDNJF3A=,iv:dy2F71WkIMFKuvrpYVPJIUC0GBLbz/2xG/ZqryTDHsE=,tag:AFj1Vqs0XyKkI7z/d33b9Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OTBYeTZ5cE9RN0I5OE84
            NnJKQ2c2UzBaUW1hQlA4dm9FYWloTUZWblhZCi9Uczl4RTRzdi9YZDd2aUJIckdC
            eW9ndVNYdlUrbUVVVVV6M3dWT2pQVTAKLS0tIHV1VU8yY0dlamZqM05DUlp4TFBn
            Z3dIc0YzVXExOWtzQ3RMbjdEUENPU0kK57v6ZzWZi1//t9dIwkDBOrZhcpFCVmzI
            G0doCnSBPCmCyqgHH3UWi4emesiuZj2HqeANMW/9T86kPvxgYj3QTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T13:29:40Z"
    mac: ENC[AES256_GCM,data:Yd9Z2AUOR0dmEBMnIePOpXpBRpfg+65RUjLnWu1rquAt708raLJRKleWCKnA37E8gDh6f1joVpZQCfDY7b5URLtY2D7o12MahRNBF+pNUOnGWV/wloBw2r/bAoe1YC1jPY8UP5scQBc0yXGNVrHH92wsO0Mnbc3VrviMJVDRiP0=,iv:ddJs05JaU4JALjNJ76P++iKNMUyJGoFJO2qWckip82Q=,tag:7a2O7/xdnf3o0L5uHwobPw==,type:str]
    version: 3.13.3
