apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0wPixkVWnAyp83UgeO5NSqo6e6UQxo9fUI8tZbwjKGgcSvSJu6UZDbk1/ir1Id1H9Fi8a6f2dUeqeDGEf0vo2B0MsQOBNIYE0oNqWDM63fiwFTKeU7cp4KIOMohB1jW71Ylc1xJQa1dQChd/L1m5PrzGQGacBlEgaditk9rfHRuKnROVGyctQl+2g3SWiW7z9RVMWxEpcWmOMs0Yj94L6ECX1QE44dJPhk+F8zqz9jA6RTgwi0DKDxU4PHWgT8RTh8JB8uzQ1GItYYef07kkD4pvclXibcCCYUl2fNOCqU6hMxYG2ttwetH6z3s=,iv:l73xAoF3JrULscLfHMY+RB//p80DrrEwtzUPVSFoEE4=,tag:q110JazpOVdMg+ftLa7Wow==,type:str]
kind: Secret
metadata:
    name: tunnel-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3NMODZMN1FaWnFTaVNx
            RVdld2pIbnRUTGJKWk1aM2tWUElPMzRhRkdZCnVvVjY2OWkxTVdnU2NqQ2RMSkdw
            ZUY4dWtkSEh2cHMvNGplS2d4YkRrdFUKLS0tIG40c2FOQTB6QUxnR3d2WVhXN1V0
            bEV0NStUTnlxYkFPWTlDZklKaVNyMDAKusUBRmBZHCms1SKTRNzIZg4bgqHzAepK
            xqMvZi6oJnAbGHWmfT7SAVA6GeaHuw7c0a42+okg5no0ONWvyeD6hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tfrmysjuq6qjr5edv09ypc0hvkjtj2wny7mg03xq554xmx553kqn34u52
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T11:23:54Z"
    mac: ENC[AES256_GCM,data:UeSXHI/bmSe8S3NeYEDd4avSibQYWNZWW3MwB/FM2VMYUjqPmWE7JuOfRebRNMFFkwE6+U0c/fmCg6Sz08gfqu3xbcYHWvfhWFitAyiQEATJmK7SDLAzUwjGYV96LV070RVA9FZbR8XkKvYtGXceC4QwCZTQCsJjThJEH1qH5nw=,iv:OaR26YC9SRo7G9AWP1b/omggc9tSCyU3QUyu5XmJjB0=,tag:Qgh40jlNosuHIzneifY5VQ==,type:str]
    version: 3.13.3
