apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:pN03ZPrU6tk=,iv:raO0qXR8hqejUF952ZiZeL8cBmHUaPgxsJLX1/y9/8M=,tag:lpVulbSAQxmcD47uubK+dA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:D+0H3b1gMUdDCf9bf3epGBtx64G9QnCAxelfuLswc0N1AlgZdfnq9hRl7ifMzmT+fFaMSM1iKbRXiDw+9Y6AWQ==,iv:P5G2SC7bXACZU5ePPgMvT884uNh0sdbTX2bSpCMc/iI=,tag:5HYz16qKRgMbBktuavFc6Q==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcEhkRElRV2tTMnY4a201
            dzE2WmVYUEJaV3p2M0tSV0VSYmZ4VWNCbHowCkdjZjMwR3ROa2dMTGFrZFROa1Bn
            Q0RkK1lYTjFCekd3TWc4RTFLK2c5L2sKLS0tIDI4MHVyL3FhZlNmVlQ3RHRjVndK
            ckFqQ1RWazNQcDJ6WVdzdklYcTZRTW8KH3bDD3BzMEBd77RWbmfXDucvUtbsGYHP
            gLHgmEMqseQgXhMbZy4YTdJlWTfR/JAtpWi6p+t+ZfbqwBz/bBAwvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tfrmysjuq6qjr5edv09ypc0hvkjtj2wny7mg03xq554xmx553kqn34u52
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T11:41:17Z"
    mac: ENC[AES256_GCM,data:b28kKThPVqAFe8BLd9Q6Qn9+rEnjyjtVnGplj8SkuO+nV/pcjmtMkkS0CG670zEGtOPqICtYyfiUecRVeKBxM+udpEUePhhvPmSf/s2wd7myc5HAsL/TuToVGaBZk67tlf1GrvxHwdEbXGG3L9qhcd7fv6Tnazl72b6vzX9Sdas=,iv:75R4xr+0E73w+s+B7nLZ/ffY6mxbNdk+rE6TBilnV5E=,tag:7jU4zf/sBDQmKOQ8mjUVKA==,type:str]
    version: 3.13.3
