apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:xPnHTJcA0UY=,iv:NEZlCyXtRNLuSzKOPfAfC8Ckwje9ctYm//Ixbnh8m3Q=,tag:7PuO6ZIqpUhrYCcyCHautA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:l4ZfGWRj4AhpdWFg5xV0otXBcOCCHBEDQD+wtAeXDg2rt0kTQ+qTIQBTMcNB+fg62HClQUsEUYw=,iv:bxnWq+1/yOUUw8CGla9oEJPx7BMz0Jf9PA5/vWXwSQM=,tag:S50wIIMGmFOOUgnemv3VHQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1lad1FBUXQwbzgwRTVX
            WFNZeGp4SWJldnptWFVmcnNMVTh6cXg1M0VjCmJkWXFYUmFwTFhzNHhtOXNudVQw
            QlZETnowb21ydFdheWJGdktlZlA1aFUKLS0tIENkeUF2L3hBSDVlTytJUW4zUHk4
            REVacGtWWDRWNFJnLy8vbVBPaWh3eUkKEEztJfNrRMgmMh6g0Mm1vPPPGP72bEzN
            EDl7QpxskEa8CXQy23HDBjImGTnn9FlKxkbyDXo67QwffLEZegt4VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T13:31:43Z"
    mac: ENC[AES256_GCM,data:w/6KS15zGZ6KuqzVtJLib3XIfUzeUcnmlcSlBFfIcm6yxPU5izb33kQwMkCLEGnabEyzDOfqaMAjriDceJON3L+wVwPm2JaiokgLenHSHiGPOrda0Ql6pLPqIufkSfE1++rFEHFB/DyEgtN6izfhPB/EOwUyf/F3mSvLX/Cgr2A=,iv:ofMtUcYBCYxUNlJI+ls3YzeT4qBYbJhyqLSzoheXunk=,tag:BBwr7LhtigywIvqmLqLg2g==,type:str]
    version: 3.13.3
