apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:DvprBIb7g/Q=,iv:2Pwg6sakDSwG+vL1t9zqSDGkZzLQrvJeg/HyE9hO0zQ=,tag:EX4bMNF2tsa3TNkrT3jSzw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:XhTA17hmwdKsGb3cJMDzouwWWnlCkvcC9ckR5NCoFgto01fS+eZ9Y0pUmZDbUE89,iv:zCfOJQj6Gf86ny/QlQaKkKh0glNijEjYd4nBHvfI45U=,tag:zEZX8lA8mcFibnRmACGLuA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWxzVXI1M2QrbEo0VEtz
            NVY3SWFjU2ZCNkx6a2VVOTY4TW04Mk9NeDBnCnFnMTJHOUhQeTVLdktOQVB3UzNt
            Q25yN3hrY2ZhRk4vWGJOVHlxNUdkZHMKLS0tIFZ1NGN2aG0xMU96dXNTR01Fb1lh
            dHpBWU9FYWY5dm43TXZTM2w5STFDRkkK3n+Qft2OjMQfmmZNdWtAxPRBAfhAyw/t
            SQQzWoFmFOMK6MipkNi1YC67e9qrmDT29pIdLRwIWnwb4GM5y1OJtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfc40eatmnux48n6mcz5vuczpmkyy4h08lnqugqnlt04kafqr9xqah45hc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T10:05:59Z"
    mac: ENC[AES256_GCM,data:rrEtmM4D6Px7qUt/KQaKGy+jlQni5pe57yoI2HZkzDPz0TM+VO01wbSyqXlX6xkyDg2tFhATw3W9PSaOlzrGtXjEBnkXqwxx0ydZn2AkJUywLXXDzEHaV9H4Xt+U1++/fDnYgSIABEoL6mt8vjyXJzOcuXH/sWoZfpuhzQAKu/s=,iv:axVXItQnnWB6CVL9U7w9hgOxOZBpJxY7PdYTiABDuC4=,tag:0PkuL6dWJYhC+u4rkJ0E8A==,type:str]
    version: 3.13.3
