apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:1AuW3VzaVvhn126+NvEBx+L8sZus9E6Y5/BwSWx+ylWnA6ohZ9obYuAjoD8u5Sdw/EGVW98+A5k=,iv:8T3OgKMaGjJuZ8DBS0V6P962Ucx0HpVz1D/rESR9H6s=,tag:N8k2Bxnqhpt/lK8nllrAbQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YWhXNmxWUHhzZjVwSU5w
            V25udjJweDFCUzlOVFhVaFBXV1NZRWJrcm13CjJadmljaktSb3duMWoyMEo5Qjd1
            ekwzcE1JMSs5K0JYZDd1RW4reUVQNzgKLS0tIGRrMWM2SE4wRmROc25rNlZoNHVD
            NEd6VFJtUFZvZVkxSG5WSVdaNUJxT2MKAOPwGaFvL+c/s8FeoZR0hMOXq5ZxWaZ3
            /3kfFY405cBqYcQuK1xMOZnzLaHjw58DTPeulhdk6O9ssPeX3aoD7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137de97ph5npwgyx9254za2kep6l04wna66zr8pt5z68ss0sy5asqm9um7p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T13:25:42Z"
    mac: ENC[AES256_GCM,data:bFheAYEKoc+tSzOJcltvsb6QGdTlk5rFvzggto8b97Ynyr1RN3kohIGzRE/w0akAR9LI6zOmTOJtzjYqoGjpDcaTOgPrsAck/P2aLKTEfV1eN5Wh9PprY4oPUzxNqORtwJFj+zMOo4G8Eodr39fKWWCZFht9d3QMzrevsKy9TmU=,iv:3R6A8sDnXa9AUfT3tZgrJJJs6w/4pLu6HM+fXAxkqSI=,tag:9KSU+BJhahpfXbGuJjtphg==,type:str]
    version: 3.13.3
